### ISSUE TITLE
Skid 2

### ISSUE THREAD

**Issue by 1337-0** [O-ffender/Fastest-Discord-Nuker#4]
Golang, rust and js are faster langs then python !!

**Comment by TKperson** [comment]
First off, I don't think this is a skid as long as he mentioned me somewhere (im fine with it)

For your last statement: how is python bot the fastest bot i think you aren't the only one that ask it go see:
 * https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/issues/16
 * https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/issues/38
